buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

// Blok 'allprojects { repositories { ... } }' dihapus dari sini
// karena lokasi repositori sudah dikelola secara otomatis dan terpusat di settings.gradle
